### PR TITLE
Remove references to crane-proxy configmap, temporarily allow navigation without validating credentials

### LINKED ISSUE #31: Cannot configure crane-proxy when running as non-admin
If I am not an admin on the destination I receive the following error.
```
Cannot configure crane-proxy
configmaps "crane-proxy" is forbidden: User "jason" cannot get resource "configmaps" in API group "" in the namespace "openshift-migration"
```

FWIW, the proxy no longer requires use of this config-map. If nothing else does either, we can probably skip trying to access it.

### PR DESCRIPTION
**Pull request by mturley**
Resolves #31 

Also prevents errors on the first wizard step from blocking wizard navigation, as a temporary workaround for #30.

### CODE REVIEW

**Comment by jmontleon** [comment]
I am just getting `http: proxy error: http: no Host in request URL` from the openshift console log with this PR. I'm looking to see if I can figure out what's going wrong, but haven't figured it out yet.

**Comment by mturley** [comment]
Trying to test on my end too, I'm not sure if I updated the crane-reverse-proxy correctly but with these changes it gives me a 503 when it tries to hit the proxy. I'm not seeing the error you're seeing in the console though.

**Comment by jmontleon** [comment]
502 errors are my fault. When logged in as a non-admin the oc get command to return the route url is returning nothing because it can't access it.

**Comment by mturley** [comment]
Ah. Should we note in the readme that you have to find that URL and paste it in instead of using the inline `oc get` if you're starting it as non-admin? Or maybe we just only support admin for local development?

**Pull request merged**
